### ISSUE TITLE
Failed to create a module and a new app

### ISSUE THREAD

**Issue by mbenencase** [PythonNest/PyNest#86]
Hi, I installed the latest (I believe) CLI version through:

```
pip3 install pynest-api
```

According to the README.md, to create a new app we should:

```
pynest generate appplication -n my_app_name
```

However, the `appplication` was wrongly typed. But, assuming that the correct is:

```
pynest generate application -n my_app_name
```

I received the following error:

```
Error: No such command 'generate'.
```

So, ok, then I ran:

```
pynest --help
```

And it threw me the following:

```
Usage: pynest [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  create-nest-app  Create a new nest app.
  g                Generate boilerplate code.
```

Now, if I ran `pynest create-nest-app` it creates the following folder structure:

```
mbenencase@Pingo:~/projects/quick/api$ pynest create-nest-app
. None False
Generate file:  settings
Generate file:  main
Generate file:  app
Generate file:  README
Generate file:  requirements
Generate file:  __init__
```

Then, according to the README.md, it says to run the following to create a new resource:

```
pynest generate resource -n users
```

However, there's no `generate` in the CLI, only `g`. So ok, let's run `pynest g module users`

```
mbenencase@Pingo:~/projects/quick/pynest$ pynest g module users
Usage: pynest g module [OPTIONS]
Try 'pynest g module --help' for help.

Error: Got unexpected extra argument (users)
```

Ok, I tried also without `users` argument:

```
mbenencase@Pingo:~/projects/quick/pynest$ pynest g module
Traceback (most recent call last):
  File "/home/mbenencase/.local/bin/pynest", line 8, in <module>
    sys.exit(nest_cli())
  File "/home/mbenencase/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/mbenencase/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/mbenencase/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mbenencase/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mbenencase/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mbenencase/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mbenencase/.local/lib/python3.10/site-packages/nest/cli/cli.py", line 70, in generate_modu
le
    create_nest_module(name=name)
  File "/home/mbenencase/.local/lib/python3.10/site-packages/nest/cli/click_handlers.py", line 65, in cr
eate_nest_module
    template = template_factory.get_template(
  File "/home/mbenencase/.local/lib/python3.10/site-packages/nest/common/templates/templates_factory.py"
, line 22, in get_template
    return BlankTemplate(module_name=module_name)
  File "/home/mbenencase/.local/lib/python3.10/site-packages/nest/common/templates/blank_template.py", l
ine 9, in __init__
    super().__init__(module_name)
  File "/home/mbenencase/.local/lib/python3.10/site-packages/nest/common/templates/base_template.py", li
ne 20, in __init__
    self.split_module_name, self.capitalized_module_name = get_module_strings(
  File "/home/mbenencase/.local/lib/python3.10/site-packages/nest/common/templates/base_template.py", li
ne 12, in get_module_strings
    split_module_name = module_name.split("_")
AttributeError: 'NoneType' object has no attribute 'split'
```

And basically I'm not sure what to do anymore 😅 .

System specs:

- Python 3.10.12
- Ubuntu 22.04
- Processor arch: x86

**Comment by ItayTheDar** [comment]
Hi @mbenencase 
Sorry that this was your experience with pynest. I believe that the issue is that you are using old version of pynest (even though it seems that you didn't specify any version when pip install so it should pull the latest.

Could you share with me the output of the command: pip list | grep pynest.

And also, if you are not working with venv, then maybe you download pynest in the past, and when you try to generate application it's still using the old version.

**Comment by mbenencase** [comment]
@ItayTheDar that was exactly the problem, I installed in other computer and it installed the most recent version. In my personal computer I have the version 0.1.2 :sweat_smile:
